export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS";
export const UPDATE_COURSES_SUCCESS = "UPDATE_AUTHORS_SUCCESS";
